#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
usage: verify-source-manifest.sh [--update] [repo-root]

Maintains apps/quiz/quiz-vulkan/cmake/quiz-vulkan-source-manifest.txt as the
generated inventory of tracked C/C++ source, header, and inline files under the
quiz-vulkan src/ and tests/ trees.
USAGE
}

update=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --update)
      update=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="${1:-$(git -C "${script_dir}/.." rev-parse --show-toplevel)}"
manifest="${repo_root}/apps/quiz/quiz-vulkan/cmake/quiz-vulkan-source-manifest.txt"

generate_manifest_body() {
  git -C "${repo_root}" ls-files \
    'apps/quiz/quiz-vulkan/src/*' \
    'apps/quiz/quiz-vulkan/tests/*' |
    grep -E '\.(c|cc|cpp|h|hh|hpp|inl)$' |
    LC_ALL=C sort
}

tmp_expected="$(mktemp)"
tmp_actual="$(mktemp)"
trap 'rm -f "${tmp_expected}" "${tmp_actual}"' EXIT

{
  echo "# Generated by codex-workers/verify-source-manifest.sh --update"
  echo "# One tracked quiz-vulkan C/C++ source, header, or inline path per line."
  generate_manifest_body
} > "${tmp_expected}"

if [[ "${update}" -eq 1 ]]; then
  mkdir -p "$(dirname "${manifest}")"
  cp "${tmp_expected}" "${manifest}"
  echo "updated source manifest: ${manifest}"
  exit 0
fi

if [[ ! -f "${manifest}" ]]; then
  echo "missing source manifest: ${manifest}" >&2
  echo "run: codex-workers/verify-source-manifest.sh --update" >&2
  exit 1
fi

grep -v '^#' "${manifest}" | sed '/^[[:space:]]*$/d' > "${tmp_actual}"
generate_manifest_body > "${tmp_expected}"

if ! diff -u "${tmp_expected}" "${tmp_actual}"; then
  echo "quiz-vulkan source manifest is stale: ${manifest}" >&2
  echo "run: codex-workers/verify-source-manifest.sh --update" >&2
  exit 1
fi

echo "source manifest OK: ${manifest}"
