// Aggregate compile-time interface lock. Individual contract fragments live near
// the owning subsystem; this file is the single target humans and agents build.

#include "../audio/audio_engine_interface_contract_tests.cpp"
#include "../app/app_render_pipeline_interface_contract_tests.cpp"
#include "../app/app_sound_router_interface_contract_tests.cpp"
#include "../assets/deck_source_asset_adapter_interface_contract_tests.cpp"
#include "../assets/asset_resolver_interface_contract_tests.cpp"
#include "../domain/deck_source_interface_contract_tests.cpp"
#include "../input/input_engine_interface_contract_tests.cpp"
#include "../layout/layout_placer_interface_contract_tests.cpp"
#include "../persistence/learning_state_store_interface_contract_tests.cpp"
#include "../platform/platform_shell_interface_contract_tests.cpp"
#include "../render/image/image_engine_interface_contract_tests.cpp"
#include "../render/text/text_engine_interface_contract_tests.cpp"
#include "../render/vulkan/vulkan_backend_interface_contract_tests.cpp"
#include "../scene/scene_modifier_interface_contract_tests.cpp"
#include "../theme/theme_tokens_interface_contract_tests.cpp"
#include "../ui/ui_renderer_interface_contract_tests.cpp"
#include "../workers/external_worker_artifact_interface_contract_tests.cpp"
